### ISSUE TITLE
Password Login Authentication

### ISSUE THREAD

**Issue by deadly990** [Jayy001/PyFactoryBridge#1]
The Satisfactory documentation indicates that third party tools should not use the PasswordLogin API, and instead should have the servers generate a long lived Application authentication token via the console's server.GenerateAPIToken function.
It would be nice if it were an option at init to provide that token directly, instead of providing a password.

**Comment by Jayy001** [comment]
I complete agree, thanks for raising this issue. I'll work on this now.

**Comment by Jayy001** [comment]
@deadly990 Could you try now using `token=xyz`?
